name: Project Automation

on:
  issues:
    types: [opened, edited, closed, reopened, labeled]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      projects: write
    steps:
      - name: Sync issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/ludwa6/projects/2
          github-token: ${{ secrets.PROJECTS_TOKEN }}
